app_index:
  path: /
  controller: App\Controller\AppController::index

app_start_random_test:
  path: /start
  controller: App\Controller\AppController::start

app_start_test:
  path: /start/{test_number}
  controller: App\Controller\AppController::start
  requirements:
    test_number: \d+

app_end_test:
  path: /end
  controller: App\Controller\AppController::end

app_answer:
  path: /answer/{answer_number}
  controller: App\Controller\AppController::answer
  requirements:
    answer_number: \d+

app_next_question:
  path: /next-question
  controller: App\Controller\AppController::nextQuestion

app_goto_question:
  path: /question/{question_number}
  controller: App\Controller\AppController::gotoQuestion
  requirements:
    answer_number: \d+
